### ISSUE TITLE
SpecVal status in the database

### ISSUE THREAD

**Issue by vaishav** [ices-eg/WGDG#14]
Status of the Specval used in the DATRAS

**Comment by vaishav** [comment]
Table found :-
https://community.ices.dk/ExpertGroups/WGDG/_layouts/15/start.aspx#/2022%20Meeting%20Documents/Forms/Allitems1.aspx?RootFolder=%2FExpertGroups%2FWGDG%2F2022%20Meeting%20Documents%2F04%2E%20Working%20documents&FolderCTID=0x012000F56FB0330418724BBA5F50F2CF2A2A05&View=%7BBB3F8620%2DB8E9%2D4174%2DA02E%2DB8D06D58F230%7D

**Comment by odontaster** [comment]
WGDG agreed to review the SpecVal descriptions. To do so, we need to check data submitted with the different SpecVal and make sure with submitters that the change in the description still applies to their data.

**Comment by odontaster** [comment]
![14bdb3ca-c5ee-40d9-8b69-5683ced30661](https://user-images.githubusercontent.com/18613829/206478511-71335a63-345a-475a-8851-1ae4ea36e0b4.jpg)

**Comment by odontaster** [comment]
[SpecVal_rev.csv](https://github.com/ices-eg/WGDG/files/10186535/SpecVal_rev.csv)

**Comment by Ingeborg1312** [comment]
I've added a sheet to http://community.ices.dk/ExpertGroups/WGDG/2022%20Meeting%20Documents/04.%20Working%20documents/Specval_status_in_Datras.xlsx?web=1 where comments on the SpecVal descriptions can be provided, for final decision on WGDG 2023-01

**Comment by odontaster** [comment]
Follow comments from Heleen. Remove 3.
0 and 9 not to be used in DATRAS data products.
Check with Spain how to better describe number 2, for which products.
Ask feedback to survey groups and confirm in WGDG-2

**Comment by odontaster** [comment]
[Specval_status_in_Datras.xlsx](https://github.com/ices-eg/WGDG/files/11000070/Specval_status_in_Datras.xlsx)

**Comment by Ingeborg1312** [comment]
WGBEAM suggests that the following information is added to the DATRAS specval descriptions:
o	specval=5: use in DATRAS product: yes, it is recommended that a comment ‘presence-absence only’ is added;
o	specval=6; use in DATRAS product: yes, it is recommended that the weight is summed up per species per haul (length=-9, number=-9, weight=SUM(catcatchwght). NB this means an additional parameter in the CPUE product file;
o	specval=8; use in DATRAS product: yes, it is recommended that the weight is summed up per species per haul (length=-9, number=-9, weight=-9, volume=SUM(catcatchwght). NB this means an additional parameter in the CPUE product file;
o	specval=10; use in DATRAS product: yes.
