### ISSUE TITLE
Request from WGACOUSTICGOV: review of LengthCode field descriptions and use

### ISSUE THREAD

**Issue by odontaster** [ices-eg/WGDG#19]
In ACOUSTIC governance we are reviewing the biotic format to make sure is fit for purpose. This code is a bit confusing and as it comes directly from DATRAS it would be good to give them feed back on the use of it, and in case, if descriptions can be improved for clarity.

**Comment by odontaster** [comment]
https://github.com/ices-eg/wg_WGACOUSTICGOV/issues/47

**Comment by odontaster** [comment]
https://github.com/ices-eg/wg_WGACOUSTICGOV/issues/47

**Comment by Ingeborg1312** [comment]
I don't see why it is still open here. We've responded to the WGACOUSTIGOV request in December 2023, and there is a proposal. No further action for WGDG needed.
