### ISSUE TITLE
VOCAB: joint vocab for Length Measurement Types, request for review

### ISSUE THREAD

**Issue by odontaster** [ices-eg/WGDG#6]
This comes from RDBES core group. They need several new codes and RMG suggests to merge the codes used in Acoustic and Datras and create a single vocab
https://github.com/ices-eg/DIG/issues/174#

**Comment by Ingeborg1312** [comment]
I wonder if anyone in DATRAS has ever measured curved length, so maybe we could change 1-Total length unspecified into 1-Total length linear. To be checked at WGDG 2022-04

**Comment by odontaster** [comment]
Answered in RMG
