### ISSUE TITLE
WEB: Add brief descriptions to Data products drop down and review naming of Data products

### ISSUE THREAD

**Issue by odontaster** [ices-eg/WGDG#9]
Suggestion to improve user experience when downloading data and data products. We could take the chance to review some namings (Flexfile, CPUE per length per hour and swept area).

**Comment by odontaster** [comment]
[DataProductsDescriptions.xlsx](https://github.com/ices-eg/WGDG/files/8714737/DataProductsDescriptions.xlsx)

**Comment by odontaster** [comment]
The links could appear under each description, but could also be fix on the top of the page.

**Comment by odontaster** [comment]
For feedback from WGDG
[DataProductsDescriptions_sep2022.xlsx](https://github.com/ices-eg/WGDG/files/9672333/DataProductsDescriptions_sep2022.xlsx)

**Comment by Ingeborg1312** [comment]
WGDG members have been asked to propose new names and review descriptions in http://community.ices.dk/ExpertGroups/WGDG/2022%20Meeting%20Documents/04.%20Working%20documents/DataProductsDescriptions_sep2022.xlsx

**Comment by vaishav** [comment]
Need to review not only the display name but also description of the product,

**Comment by vaishav** [comment]
The description is available now on the web
